### ISSUE TITLE
ws origins issue

### ISSUE THREAD

**Issue by hollejacklin** [aurora-is-near/relayer2-public#116]
I try to call rpc request form ws, but it shown the error

"websocket: request origin not allowed by FastHTTPUpgrader.CheckOrigin","time":"2023-11-11T19:11:26+08:00","message":"error upgrading to websocket"}

I think it was  ws.origins value issue. Normally I will set it to "*", but I cannot find any key word to set it.

my config.yaml
wsHost: 0.0.0.0 # Both wsHost and wsPort are mandatory to start the websocket
wsPort: 8546 # Both wsHost and wsPort are mandatory to start the websocket
wsPathPrefix: "*" # allows all paths
wsHandshakeTimeout: 10 # in seconds
maxBatchRequests: 1000

relayer build v2.1.9

**Comment by spilin** [comment]
@hollejacklin  thank you for reporting. This should no longer be an issue
