### ISSUE TITLE
cannot send tx

### ISSUE THREAD

**Issue by hollejacklin** [aurora-is-near/relayer2-public#84]
Hi, I had run the relayer2, and I tried to fine tune the config.
When I change the indexer.keepFiles to false to save my ssd storage,but I found I cannot send tx through relayer2. Was keep refiner json file necessary?

In addition, when I keep the indexer.keepFiles to true, the relayer2 can send tx normally, but it also rarely cannot send out my tx about send 20 txs 1 will miss.

**Comment by akeyder** [comment]
Hi @hollejacklin 
the `indexer.keepFiles` config is not related to tx sending, we nevertheless verified that it is not reproducible in our tests setups. For further investigation, can you please share the followings;
* have you used [standalone-rpc](https://github.com/aurora-is-near/standalone-rpc) for installation of relayer2 and [refiner](https://github.com/aurora-is-near/borealis-engine-lib) or have you installed them from scratch 
* can you please share the config file you are using and logs while having the issue

thanks!

**Comment by hollejacklin** [comment]
Hi @akeyder 
I installed refiner(borealis-engine-lib v0.18.0) and relayer2(v2.0.0) separately.
I just try it again using indexer.keepFiles=false, and it send tx normally. I will test it for long time for more information.

if I found it didn't send out the tx, the log report the near tx hash and aurora tx hash, but I cannot found it on aurora explorer and near explorer. it looks like the tx was made but the tx was on chain. However I send the same tx to my relayer-V1 at same time was normally. (I run relayer V1 and V2 at the same time for backup line)

**Comment by akeyder** [comment]
Hi @hollejacklin 
the txns you send either via relayer v1 or v2 are using the same path to reach the chain and communicating with same contract so I would not expect any problem there. But this part of your comment caught my attention
```
I send the same tx to my relayer-V1 at same time was normally. (I run relayer V1 and V2 at the same time for backup line)
```
what exactly do you mean by sending `same txn at the same time` from both relayers (v1 and v2)?
I am not sure how such request is processed but it may cause some kind of race condition hence undefined behavior. 
please explain your setup (topology) in more details and also would be great to have logs if it is reproduced again.

thanks

**Comment by hollejacklin** [comment]
Hi @akeyder,
The following was my relayers and app structure.
app1(javascript VM1)->relayer-V1(VM1)->nearcore(VM1)->WAN_IP1
app1(javascript VM2)->relayer-V2(VM2)->refiner_nearcore(VM2)->WAN_IP2

app1 in VM1 and VM2 used same aurora account and same function. If app1 send out a tx from VM1 and VM2, the relayer-V1 and relayer-V2 will feed back same tx hash. However, sometimes only the app1(VM1) can get receipt, the app1(VM2) get nothing.

**Comment by akeyder** [comment]
Hi @hollejacklin 
unless you have already changed it in config,  relayer2 sends txns in `async` fashion by default, while relayer1 sends them in `sync`. I suspect this may cause timing related issues in your app1 logic so;
1. can you please change the relayer2 config `endpoint.engine.asyncSendRawTxs` to `false` and restart relayer2 and perform the same test again.
2. if this still not helps, I would recommend running the same tests with only relayer2 if possible

**Comment by hollejacklin** [comment]
It looks for setting endpoint.engine.asyncSendRawTxs to false.
Thanks.
